# Generated by Django 3.0 on 2019-12-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trains',
            name='tr_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
