# Generated by Django 3.0 on 2019-12-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcs', '0002_trains_tr_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='trains',
            name='tr_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
