# Generated by Django 3.0 on 2019-12-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcs', '0004_auto_20191216_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trains',
            name='arr',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trains',
            name='dep',
            field=models.DateTimeField(),
        ),
    ]
