# Generated by Django 3.0 on 2019-12-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcs', '0006_auto_20191216_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trains',
            name='duration',
            field=models.CharField(max_length=10),
        ),
    ]
